database:
  user: "postgres"
  password: "postgres"
  host: "shopflow-ctw04526-db.cpo4k6euqs4p.eu-central-1.rds.amazonaws.com"
  port: 5432
  name: "postgres"

aws:
  region: "eu-central-1"
  bucket: "04526-shopflow-bucket"
  profile: "data-academy"